name: Test specification
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
permissions:
  contents: read
  issues: write 
jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: npm run test
      - run: |
          RESULTS=$(cat ./latest.log)
          echo "RESULT=$RESULT" >> $GITHUB_ENV
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULTS:
        with:
          update_existing: true