name: Test specification
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'
permissions:
  contents: read
  issues: write 
jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: npm install
      - run: |
          curl https://raw.githubusercontent.com/vrchatapi/specification/gh-pages/openapi.yaml -o openapi.yaml

          rm .cache -rf
          mkdir ./.cache

          ava reset-cache

          ./node_modules/.bin/ava --serial